FROM node:12
# Create app directory
WORKDIR /app
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
COPY yarn*.lock ./
COPY . .
RUN yarn
RUN yarn check:server
RUN yarn test:server
RUN yarn build:server
EXPOSE 4000
CMD [ "yarn", "start:server" ]


